version: '3.4'

networks:
  backNetwork:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password1!"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - backNetwork

  distributionsmartenergybackapp:
    image: ${DOCKER_REGISTRY-}distributionsmartenergybackapp
    build:
      context: .
      dockerfile: DistributionSmartEnergyBackApp/Dockerfile
    environment:
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "Password1!"
      DatabaseName: "DocumentDB"
    ports:
      - "24885:80"
    networks:
      - backNetwork

  distributionsmartenergyusermicroservice:
    image: ${DOCKER_REGISTRY-}distributionsmartenergyusermicroservice
    build:
      context: .
      dockerfile: DistributionSmartEnergyUserMicroservice/Dockerfile
    environment:
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "Password1!"
      DatabaseName: "UserDB"
    ports:
      - "28543:80"
    networks:
      - backNetwork

  notificationmicroservice:
    image: ${DOCKER_REGISTRY-}notificationmicroservice
    build:
      context: .
      dockerfile: NotificationMicroservice/Dockerfile
    environment:
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "Password1!"
      DatabaseName: "NotificationDB"
    ports:
      - "35827:80"
    networks:
      - backNetwork

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: API gateway/Dockerfile
    ports:
      - "24757:80"
    networks:
      - backNetwork
