version: '3.4'

networks:
  backNetwork:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password1!"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - backNetwork

  distributionsmartenergybackapp:
    image: ${DOCKER_REGISTRY-}distributionsmartenergybackapp
    build:
      context: .
      dockerfile: DistributionSmartEnergyBackApp/Dockerfile
    environment:
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "Password1!"
      DatabaseName: "DocumentDB"
      DAPR_GRPC_PORT: "40001"
    ports:
      - "24885:80"
      - "40001:40001"
    networks:
      - backNetwork

  distributionsmartenergybackapp-dapr:
       image: "daprio/daprd:latest"
       command: [ "./daprd", "-app-id", "distributionsmartenergybackapp", "-app-port", "80", "-dapr-grpc-port", "40001" ]
       depends_on:
        - distributionsmartenergybackapp
       network_mode: "service:distributionsmartenergybackapp"



  distributionsmartenergyusermicroservice:
    image: ${DOCKER_REGISTRY-}distributionsmartenergyusermicroservice
    build:
      context: .
      dockerfile: DistributionSmartEnergyUserMicroservice/Dockerfile
    environment:
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "Password1!"
      DatabaseName: "UserDB"
      DAPR_GRPC_PORT: "40003"
    ports:
      - "28543:80"
      - "40003:40003"
    networks:
      - backNetwork

  distributionsmartenergyusermicroservice-dapr:
       image: "daprio/daprd:latest"
       command: [ "./daprd", "-app-id", "distributionsmartenergyusermicroservice", "-app-port", "80", "-dapr-grpc-port", "40003" ]
       depends_on:
        - distributionsmartenergyusermicroservice
       network_mode: "service:distributionsmartenergyusermicroservice"        
  

  notificationmicroservice:
    image: ${DOCKER_REGISTRY-}notificationmicroservice
    build:
      context: .
      dockerfile: NotificationMicroservice/Dockerfile
    environment:
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "Password1!"
      DatabaseName: "NotificationDB"
      DAPR_GRPC_PORT: "40005"
    ports:
      - "35827:80"
      - "40005:40005"
    networks:
      - backNetwork

  notificationmicroservice-dapr:
       image: "daprio/daprd:latest"
       command: [ "./daprd", "-app-id", "notificationmicroservice", "-app-port", "80", "-dapr-grpc-port", "40005" ]
       depends_on:
        - notificationmicroservice
       network_mode: "service:notificationmicroservice"    


  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: API gateway/Dockerfile
    ports:
      - "24757:80"
    networks:
      - backNetwork
